name: 'Claude Code Changelog'
description: 'Generate changelog using Claude Code based on git diff from last tag'
author: 'mistricky'
branding:
  icon: 'file-text'
  color: 'orange'

inputs:
  github_token:
    description: 'GitHub token with repo access'
    required: true
    default: ${{ github.token }}
  anthropic_api_key:
    description: 'Anthropic API key for Claude'
    required: false
  small_fast_model:
    description: 'Use small fast model for Claude'
    required: false
    default: ''
  api_base_url:
    description: 'API base URL for Claude (optional, defaults to Anthropic API)'
    required: false
  from_tag:
    description: 'Start tag for diff (defaults to latest tag)'
    required: false
  to_ref:
    description: 'End reference for diff'
    required: false
    default: 'HEAD'
  model:
    description: 'Claude model to use'
    required: false
    default: 'claude-3-5-sonnet-20241022'
  use_bedrock:
    description: 'Use Amazon Bedrock'
    required: false
    default: 'false'
  use_vertex:
    description: 'Use Google Vertex AI'
    required: false
    default: 'false'
  bedrock_region:
    description: 'AWS Bedrock region'
    required: false
    default: 'us-east-1'
  vertex_project_id:
    description: 'Google Cloud Project ID'
    required: false
  vertex_region:
    description: 'Google Cloud region'
    required: false
    default: 'us-central1'

outputs:
  changes_count:
    description: 'Number of changes analyzed'
    value: ${{ steps.output.outputs.changes_count }}
  from_tag:
    description: 'Starting tag used for analysis'
    value: ${{ steps.output.outputs.from_tag }}
  to_ref:
    description: 'Ending reference used for analysis'  
    value: ${{ steps.output.outputs.to_ref }}

runs:
  using: 'composite'
  steps:
    - name: Get previous tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: '0.0.0'

    - name: Prepare git diff for Claude analysis
      id: prepare
      shell: bash
      run: |
        # Get the from tag if not specified
        if [ -z "${{ inputs.from_tag }}" ]; then
          FROM_TAG="${{ steps.previoustag.outputs.tag }}"
        else
          FROM_TAG="${{ inputs.from_tag }}"
        fi
        
        TO_REF="${{ inputs.to_ref }}"
        
        echo "from_tag=$FROM_TAG" >> $GITHUB_OUTPUT
        echo "to_ref=$TO_REF" >> $GITHUB_OUTPUT
        
        # Get git log and diff
        echo "Getting changes from $FROM_TAG to $TO_REF"
        
        # Create comprehensive diff analysis
        git log --pretty=format:"%h - %s (%an, %ar)" "$FROM_TAG..$TO_REF" > /tmp/commits.log || true
        git diff --stat "$FROM_TAG..$TO_REF" > /tmp/diff_stat.log || true
        git diff "$FROM_TAG..$TO_REF" > /tmp/full_diff.log || true
        
        # Count commits and files
        COMMIT_COUNT=$(git rev-list --count "$FROM_TAG..$TO_REF" 2>/dev/null || echo "0")
        echo "changes_count=$COMMIT_COUNT" >> $GITHUB_OUTPUT
        
        # Create analysis prompt for Claude with actual commit data
        cat > /tmp/changelog_prompt.md << EOF
        You are a technical writer creating a changelog for a software project.

        Please analyze the following git changes and generate a professional changelog in markdown format.

        ## Commits from $FROM_TAG to $TO_REF:
        \`\`\`
        $(cat /tmp/commits.log 2>/dev/null || echo "No commits found")
        \`\`\`

        ## File Changes Summary:
        \`\`\`
        $(cat /tmp/diff_stat.log 2>/dev/null || echo "No file changes found")
        \`\`\`

        ## Detailed Changes (first 200 lines):
        \`\`\`
        $(head -200 /tmp/full_diff.log 2>/dev/null || echo "No detailed changes available")
        \`\`\`

        ## Instructions:
        1. **Categorize changes** using standard changelog categories:
           - **Added**: New features
           - **Changed**: Changes in existing functionality
           - **Deprecated**: Soon-to-be removed features
           - **Removed**: Removed features
           - **Fixed**: Bug fixes
           - **Security**: Security improvements

        2. **Write clear, user-focused descriptions** that explain:
           - What changed from a user's perspective
           - Why it matters
           - Any breaking changes or migration notes

        3. **Use consistent formatting**:
           - Each item should be a concise bullet point
           - Start with an action verb when possible
           - Group related changes together

        4. **Focus on semantic meaning** rather than technical implementation details

        Generate only the changelog content in markdown format without any explanatory text or metadata. Do not include version numbers or dates.
        EOF

    - name: Generate changelog with Claude Code Base Action
      id: claude
      uses: anthropics/claude-code-base-action@beta
      with:
        claude_env: |
          ANTHROPIC_AUTH_TOKEN: ${{ inputs.anthropic_api_key }}
          ANTHROPIC_BASE_URL: ${{ inputs.api_base_url }}
          ANTHROPIC_MODEL: ${{ inputs.model }}
          ANTHROPIC_SMALL_FAST_MODEL: ${{ inputs.small_fast_model }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        use_bedrock: ${{ inputs.use_bedrock }}
        use_vertex: ${{ inputs.use_vertex }}
        bedrock_region: ${{ inputs.bedrock_region }}
        vertex_project_id: ${{ inputs.vertex_project_id }}
        vertex_region: ${{ inputs.vertex_region }}
        model: ${{ inputs.model }}
        allowed_tools: "Bash(git:*),Read,Write,Edit"
        prompt_file: /tmp/changelog_prompt.md

    - name: Set outputs
      id: output
      shell: bash
      run: |
        # Get the changelog content from Claude's output (should be printed to stdout)
        # The claude-code-base-action will have already executed and generated output
        
        # Set basic outputs
        echo "changes_count=${{ steps.prepare.outputs.changes_count }}" >> $GITHUB_OUTPUT
        echo "from_tag=${{ steps.prepare.outputs.from_tag }}" >> $GITHUB_OUTPUT  
        echo "to_ref=${{ steps.prepare.outputs.to_ref }}" >> $GITHUB_OUTPUT
        
        # Note: The actual changelog content will come from Claude's direct output
        # No file persistence needed - Claude will output the changelog directly
