name: 'Claude Code Changelog'
description: 'Generate changelog using Claude Code based on git diff from last tag'
author: 'CCC Team'
branding:
  icon: 'file-text'
  color: 'orange'

inputs:
  github_token:
    description: 'GitHub token with repo access'
    required: true
    default: ${{ github.token }}
  anthropic_api_key:
    description: 'Anthropic API key for Claude'
    required: false
  from_tag:
    description: 'Start tag for diff (defaults to latest tag)'
    required: false
  to_ref:
    description: 'End reference for diff (defaults to HEAD)'
    required: false
    default: 'HEAD'
  output_file:
    description: 'Output changelog file path'
    required: false
    default: 'CHANGELOG.md'
  format:
    description: 'Output format (markdown, json)'
    required: false
    default: 'markdown'
  model:
    description: 'Claude model to use'
    required: false
    default: 'claude-3-5-sonnet-20241022'
  use_bedrock:
    description: 'Use Amazon Bedrock'
    required: false
    default: 'false'
  use_vertex:
    description: 'Use Google Vertex AI'
    required: false
    default: 'false'
  bedrock_region:
    description: 'AWS Bedrock region'
    required: false
    default: 'us-east-1'
  vertex_project_id:
    description: 'Google Cloud Project ID'
    required: false
  vertex_region:
    description: 'Google Cloud region'
    required: false
    default: 'us-central1'

outputs:
  changelog:
    description: 'Generated changelog content'
  changelog_file:
    description: 'Path to the generated changelog file'
  changes_count:
    description: 'Number of changes analyzed'

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
      shell: bash
      working-directory: ${{ github.action_path }}
    
    - name: Generate changelog
      run: bun run src/main.ts
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        INPUT_FROM_TAG: ${{ inputs.from_tag }}
        INPUT_TO_REF: ${{ inputs.to_ref }}
        INPUT_OUTPUT_FILE: ${{ inputs.output_file }}
        INPUT_FORMAT: ${{ inputs.format }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_USE_BEDROCK: ${{ inputs.use_bedrock }}
        INPUT_USE_VERTEX: ${{ inputs.use_vertex }}
        INPUT_BEDROCK_REGION: ${{ inputs.bedrock_region }}
        INPUT_VERTEX_PROJECT_ID: ${{ inputs.vertex_project_id }}
        INPUT_VERTEX_REGION: ${{ inputs.vertex_region }}
        GITHUB_TOKEN: ${{ inputs.github_token }}