name: Auto Release with Changelog

on:
  push:
    tags:
      - 'v*.*.*'  # Matches v1.0.0, v2.1.3, etc.

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for git analysis

      - name: Generate Changelog
        id: changelog
        uses: ./
        with:
          from_tag: v0.1.15 
          api_base_url: https://llm.jp.one2x.ai 
          model: 'us.anthropic.claude-sonnet-4-20250514-v1:0'
          small_fast_model: 'us.anthropic.claude-3-5-sonnet-20241022-v2:0'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          output_file: 'RELEASE_CHANGELOG.md'
          format: 'markdown'

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG_CONTENT: ${{ steps.changelog.outputs.result }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            ## 🤖 AI-Generated Changelog
            
            ${{ env.CHANGELOG_CONTENT }}
            
            ---
            
            🔗 **Full Changelog**: https://github.com/mistricky/ccc/compare/${{ github.event.before || 'HEAD~1' }}...${{ steps.version.outputs.version }}  
            ⚡ **Generated with**: [CCC (Claude Code Changelog)](https://github.com/mistricky/ccc)
          draft: false
          prerelease: ${{ contains(steps.version.outputs.version, '-') }}
