name: Auto Release with Changelog

on:
  push:
    tags:
      - 'v*.*.*'  # Matches v1.0.0, v2.1.3, etc.

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for git analysis

      - name: Generate Changelog
        id: changelog
        uses: ./
        with:
          api_base_url: ${{ secrets.API_BASE_URL }} 
          model: ${{ secrets.MODEL }} 
          small_fast_model: ${{ secrets.SMALL_FAST_MODEL }} 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          format: 'markdown'

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            ## 🤖 AI-Generated Changelog
            
            ${{ steps.changelog.outputs.result }}
            
            ---
            
            🔗 **Full Changelog**: https://github.com/mistricky/ccc/compare/${{steps.changelog.outputs.from_tag}}...${{ steps.changelog.outputs.to_tag }}  
            ⚡ **Generated with**: [CCC (Claude Code Changelog)](https://github.com/mistricky/ccc)
          draft: false
          prerelease: ${{ contains(steps.version.outputs.version, '-') }}
