name: Test CCC Action

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test CCC Action
        id: test_ccc
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          output_file: 'test-changelog.md'
          format: 'markdown'
        continue-on-error: true

      - name: Check outputs
        run: |
          echo "Action completed with status: ${{ steps.test_ccc.outcome }}"
          echo "Changes count: ${{ steps.test_ccc.outputs.changes_count }}"
          echo "Changelog file: ${{ steps.test_ccc.outputs.changelog_file }}"
          
          if [ -f "test-changelog.md" ]; then
            echo "Generated changelog:"
            cat test-changelog.md
          else
            echo "No changelog file generated"
          fi

      - name: Upload test changelog
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-changelog
          path: test-changelog.md
          retention-days: 7